name: flutter_application_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4


  get: ^4.7.3
  google_fonts: ^6.3.1
  http: ^1.2.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    # - assets/images/
    - assets/icons/